spring.application.name=TalkToMe

basic.auth.username=user
basic.auth.password=password

storage.path=storage

# model paths (place models under project root models/)
tts.models.path=models

# pocket-tts model
tts.models.pocket-tts="models/pocket-tts"
tts.models.pocket-tts.tokenizer="tolkenizer.model"